### ISSUE TITLE
Change Guzzle User Agent

### ISSUE THREAD

**Issue by vgallissot** [M6Web/GuzzleHttpBundle#11]
With a more explicit one

**Comment by omansour** [comment]
hummm oui ce serait pas mal de pouvoir définir un user agent par client 

qu'en penses tu @mojoLyon  ?

**Comment by mojoLyon** [comment]
It's possible. 
What about allowing setting default request header through configuration ?
```yaml
client:
    default_headers:
         User-Agent: My agent 1.0
         X-answer: 42
```
